"""
Routing service — department assignment + queue token + Urdu explanation.

Takes a TriageResult and produces:
  - Department assignment with room/ward info
  - Queue token number
  - Estimated wait time
  - Full Urdu + English explanation for patient
  - Staff summary for nurse dashboard

FR-RTE-01, FR-RTE-02, FR-EXP-01, FR-EXP-02 from SRS.
"""

import os, logging, asyncio
from dataclasses import dataclass
from openai import AsyncOpenAI
from services.triage_agent import TriageResult

logger = logging.getLogger(__name__)

# In-memory token counter per department (resets on server restart)
# Phase 5 will move this to PostgreSQL
_token_counters: dict[str, int] = {
    "AE":      0,
    "EOPD":    0,
    "GOPD":    0,
}

DEPARTMENT_CONFIG = {
    1: {
        "code":         "AE",
        "name_en":      "Emergency — A&E",
        "name_ur":      "ایمرجنسی — A&E",
        "location_en":  "Go through the red emergency doors at the front of the building.",
        "location_ur":  "عمارت کے سامنے والے سرخ ایمرجنسی دروازوں سے اندر جائیں۔",
        "wait_mins":    0,
        "color":        "#FF3B3B",
    },
    2: {
        "code":         "AE",
        "name_en":      "Emergency — A&E",
        "name_ur":      "ایمرجنسی — A&E",
        "location_en":  "Go through the red emergency doors at the front of the building.",
        "location_ur":  "عمارت کے سامنے والے سرخ ایمرجنسی دروازوں سے اندر جائیں۔",
        "wait_mins":    15,
        "color":        "#FF8C00",
    },
    3: {
        "code":         "EOPD",
        "name_en":      "Emergency OPD",
        "name_ur":      "ایمرجنسی OPD",
        "location_en":  "Turn left after the main entrance. Emergency OPD is the first door on your left.",
        "location_ur":  "مرکزی دروازے کے بعد بائیں مڑیں۔ ایمرجنسی OPD پہلا دروازہ ہے۔",
        "wait_mins":    30,
        "color":        "#FFD600",
    },
    4: {
        "code":         "GOPD",
        "name_en":      "General OPD",
        "name_ur":      "جنرل OPD",
        "location_en":  "Take the main corridor straight ahead. General OPD registration is at the end.",
        "location_ur":  "سیدھے مرکزی راستے پر چلیں۔ جنرل OPD رجسٹریشن آخر میں ہے۔",
        "wait_mins":    60,
        "color":        "#4CAF50",
    },
    5: {
        "code":         "GOPD",
        "name_en":      "General OPD",
        "name_ur":      "جنرل OPD",
        "location_en":  "Take the main corridor straight ahead. General OPD registration is at the end.",
        "location_ur":  "سیدھے مرکزی راستے پر چلیں۔ جنرل OPD رجسٹریشن آخر میں ہے۔",
        "wait_mins":    120,
        "color":        "#90CAF9",
    },
}


@dataclass
class RouteResult:
    session_id:          str
    token_number:        str       # e.g. "AE-007", "GOPD-042"
    level:               int
    level_name:          str
    level_color:         str
    department_code:     str
    department_name_en:  str
    department_name_ur:  str
    location_en:         str
    location_ur:         str
    wait_mins:           int
    patient_message_en:  str       # Short message for kiosk screen
    patient_message_ur:  str
    explanation_en:      str       # Longer explanation generated by LLM
    explanation_ur:      str
    staff_summary:       str       # Clinical summary for nurse dashboard
    escalate_now:        bool
    requires_review:     bool


def _next_token(dept_code: str) -> str:
    """Generate next sequential token for a department."""
    _token_counters[dept_code] = _token_counters.get(dept_code, 0) + 1
    return f"{dept_code}-{_token_counters[dept_code]:03d}"


async def _generate_explanation(triage: TriageResult, dept: dict) -> tuple[str, str]:
    """
    Use GPT-4o to generate a warm, plain-language explanation for the patient
    in both English and Urdu.
    Falls back to template messages if LLM call fails.
    """
    try:
        client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))

        prompt = f"""You are a friendly hospital assistant in Pakistan.
Write a warm, simple explanation for a patient in BOTH English and Urdu.

Patient situation:
- Urgency level: {triage.level} ({triage.level_name})
- Department: {dept['name_en']}
- Estimated wait: {dept['wait_mins']} minutes
- Nurse reasoning: {triage.reasoning}

Rules:
- Use very simple everyday words (no medical jargon)
- Be calm and reassuring
- In Urdu use proper Urdu script (not Roman Urdu)
- Maximum 2 sentences each language

Return ONLY valid JSON, no markdown:
{{"english": "<2 sentence English explanation>", "urdu": "<2 sentence Urdu explanation>"}}"""

        response = await client.chat.completions.create(
            model="gpt-4o",
            temperature=0.3,
            max_tokens=300,
            messages=[{"role": "user", "content": prompt}],
        )

        import json
        raw = response.choices[0].message.content.strip()
        if "```" in raw:
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        data = json.loads(raw.strip())
        return data.get("english", ""), data.get("urdu", "")

    except Exception as e:
        logger.warning(f"Explanation LLM failed: {e} — using template")
        en = (
            f"You have been assigned to {dept['name_en']}. "
            f"Your expected wait time is approximately {dept['wait_mins']} minutes. "
            f"Please keep your token visible and listen for your number."
        )
        ur = (
            f"آپ کو {dept['name_ur']} بھیجا گیا ہے۔ "
            f"آپ کی تخمینی انتظار {dept['wait_mins']} منٹ ہے۔ "
            f"براہ کرم اپنا ٹوکن سنبھال کر رکھیں۔"
        )
        return en, ur


def _build_staff_summary(triage: TriageResult, token: str) -> str:
    """Build a concise clinical summary for the nurse dashboard."""
    lines = [
        f"TOKEN: {token} | LEVEL {triage.level} — {triage.level_name}",
        f"Complaint: {triage.reasoning}",
        f"Confidence: {triage.confidence}%",
    ]
    if triage.safety_rule_fired:
        lines.append(f"⚠ Safety rule triggered: {triage.safety_rule_name}")
    if triage.requires_review:
        lines.append("⚠ LOW CONFIDENCE — nurse review required")
    if triage.escalate_now:
        lines.append("🚨 LEVEL 1 — IMMEDIATE ESCALATION REQUIRED")
    return " | ".join(lines)


async def route_patient(triage: TriageResult) -> RouteResult:
    """
    Full routing pipeline:
      1. Assign department based on triage level
      2. Generate queue token
      3. Generate LLM explanation (Urdu + English)
      4. Build staff summary
      5. Return RouteResult

    Args:
        triage: TriageResult from the triage agent

    Returns:
        RouteResult with everything needed for kiosk result screen + dashboard
    """
    logger.info(f"Routing | session={triage.session_id} | level={triage.level}")

    dept   = DEPARTMENT_CONFIG[triage.level]
    token  = _next_token(dept["code"])

    # Generate explanation (LLM with fallback)
    explanation_en, explanation_ur = await _generate_explanation(triage, dept)

    # Short patient messages (from triage agent)
    patient_msg_en = triage.patient_message
    patient_msg_ur = triage.patient_message_ur

    # Staff summary
    staff_summary = _build_staff_summary(triage, token)

    result = RouteResult(
        session_id         = triage.session_id,
        token_number       = token,
        level              = triage.level,
        level_name         = triage.level_name,
        level_color        = dept["color"],
        department_code    = dept["code"],
        department_name_en = dept["name_en"],
        department_name_ur = dept["name_ur"],
        location_en        = dept["location_en"],
        location_ur        = dept["location_ur"],
        wait_mins          = dept["wait_mins"],
        patient_message_en = patient_msg_en,
        patient_message_ur = patient_msg_ur,
        explanation_en     = explanation_en,
        explanation_ur     = explanation_ur,
        staff_summary      = staff_summary,
        escalate_now       = triage.escalate_now,
        requires_review    = triage.requires_review,
    )

    logger.info(
        f"Routing done | token={token} | dept={dept['code']} | wait={dept['wait_mins']}min"
    )
    return result